"""
Universal Trading Strategy Schema (UTSS) v2.1

A comprehensive, composable schema for expressing any trading strategy.
Follows the Signal -> Condition -> Rule -> Strategy hierarchy.
"""

from utss.models import (
    # Enums
    Timeframe,
    Frequency,
    DayOfWeek,
    PriceField,
    CalendarField,
    PortfolioField,
    IndicatorType,
    FundamentalMetric,
    EventType,
    RelativeMeasure,
    ArithmeticOperator,
    ComparisonOperator,
    CrossDirection,
    TemporalModifier,
    ChangeDirection,
    TradeDirection,
    OrderType,
    TimeInForce,
    RebalanceMethod,
    AlertLevel,
    AlertChannel,
    ExternalSource,
    StockIndex,
    Visibility,
    ParameterType,
    # Parameter Reference
    ParameterReference,
    # Signals
    IndicatorParams,
    PriceSignal,
    IndicatorSignal,
    FundamentalSignal,
    CalendarSignal,
    EventSignal,
    PortfolioSignal,
    RelativeSignal,
    ConstantSignal,
    ArithmeticSignal,
    ExpressionSignal,
    ExternalSignal,
    Reference,
    Signal,
    # Conditions
    ComparisonCondition,
    CrossCondition,
    RangeCondition,
    AndCondition,
    OrCondition,
    NotCondition,
    TemporalCondition,
    SequenceStep,
    SequenceCondition,
    ChangeCondition,
    AlwaysCondition,
    Condition,
    # Sizing
    FixedAmountSizing,
    PercentEquitySizing,
    PercentPositionSizing,
    RiskBasedSizing,
    KellySizing,
    VolatilityAdjustedSizing,
    ConditionalSizingCase,
    ConditionalSizing,
    Sizing,
    # Actions
    TradeAction,
    RebalanceTarget,
    RebalanceAction,
    AlertAction,
    HoldAction,
    Action,
    # Rules
    Rule,
    # Universe
    StaticUniverse,
    IndexUniverse,
    ScreenerUniverse,
    DualUniverseSide,
    DualUniverse,
    Universe,
    # Constraints
    StopConfig,
    TrailingStopConfig,
    TimeStop,
    Constraints,
    # Schedule
    Schedule,
    # Parameters
    Parameter,
    # Info
    Author,
    Info,
    # Strategy
    Strategy,
)
from utss.validator import validate_strategy, validate_yaml, ValidationError
from utss.capabilities import (
    SCHEMA_VERSION,
    SUPPORTED_INDICATORS,
    SUPPORTED_FUNDAMENTALS,
    SUPPORTED_EVENTS,
    SUPPORTED_PRICE_FIELDS,
    SUPPORTED_CALENDAR_FIELDS,
    SUPPORTED_PORTFOLIO_FIELDS,
    SUPPORTED_COMPARISON_OPERATORS,
    SUPPORTED_ARITHMETIC_OPERATORS,
    SUPPORTED_CROSS_DIRECTIONS,
    SUPPORTED_TEMPORAL_MODIFIERS,
    SUPPORTED_CHANGE_DIRECTIONS,
    SUPPORTED_TRADE_DIRECTIONS,
    SUPPORTED_REBALANCE_METHODS,
    SUPPORTED_CONDITION_TYPES,
    SUPPORTED_SIGNAL_TYPES,
    SUPPORTED_ACTION_TYPES,
    SUPPORTED_SIZING_TYPES,
    SUPPORTED_UNIVERSE_TYPES,
)

__version__ = "2.1.0"
__all__ = [
    # Enums
    "Timeframe",
    "Frequency",
    "DayOfWeek",
    "PriceField",
    "CalendarField",
    "PortfolioField",
    "IndicatorType",
    "FundamentalMetric",
    "EventType",
    "RelativeMeasure",
    "ArithmeticOperator",
    "ComparisonOperator",
    "CrossDirection",
    "TemporalModifier",
    "ChangeDirection",
    "TradeDirection",
    "OrderType",
    "TimeInForce",
    "RebalanceMethod",
    "AlertLevel",
    "AlertChannel",
    "ExternalSource",
    "StockIndex",
    "Visibility",
    "ParameterType",
    # Parameter Reference
    "ParameterReference",
    # Signals
    "IndicatorParams",
    "PriceSignal",
    "IndicatorSignal",
    "FundamentalSignal",
    "CalendarSignal",
    "EventSignal",
    "PortfolioSignal",
    "RelativeSignal",
    "ConstantSignal",
    "ArithmeticSignal",
    "ExpressionSignal",
    "ExternalSignal",
    "Reference",
    "Signal",
    # Conditions
    "ComparisonCondition",
    "CrossCondition",
    "RangeCondition",
    "AndCondition",
    "OrCondition",
    "NotCondition",
    "TemporalCondition",
    "SequenceStep",
    "SequenceCondition",
    "ChangeCondition",
    "AlwaysCondition",
    "Condition",
    # Sizing
    "FixedAmountSizing",
    "PercentEquitySizing",
    "PercentPositionSizing",
    "RiskBasedSizing",
    "KellySizing",
    "VolatilityAdjustedSizing",
    "ConditionalSizingCase",
    "ConditionalSizing",
    "Sizing",
    # Actions
    "TradeAction",
    "RebalanceTarget",
    "RebalanceAction",
    "AlertAction",
    "HoldAction",
    "Action",
    # Rules
    "Rule",
    # Universe
    "StaticUniverse",
    "IndexUniverse",
    "ScreenerUniverse",
    "DualUniverseSide",
    "DualUniverse",
    "Universe",
    # Constraints
    "StopConfig",
    "TrailingStopConfig",
    "TimeStop",
    "Constraints",
    # Schedule
    "Schedule",
    # Parameters
    "Parameter",
    # Info
    "Author",
    "Info",
    # Strategy
    "Strategy",
    # Validation
    "validate_strategy",
    "validate_yaml",
    "ValidationError",
    # Capabilities (for engine sync validation)
    "SCHEMA_VERSION",
    "SUPPORTED_INDICATORS",
    "SUPPORTED_FUNDAMENTALS",
    "SUPPORTED_EVENTS",
    "SUPPORTED_PRICE_FIELDS",
    "SUPPORTED_CALENDAR_FIELDS",
    "SUPPORTED_PORTFOLIO_FIELDS",
    "SUPPORTED_COMPARISON_OPERATORS",
    "SUPPORTED_ARITHMETIC_OPERATORS",
    "SUPPORTED_CROSS_DIRECTIONS",
    "SUPPORTED_TEMPORAL_MODIFIERS",
    "SUPPORTED_CHANGE_DIRECTIONS",
    "SUPPORTED_TRADE_DIRECTIONS",
    "SUPPORTED_REBALANCE_METHODS",
    "SUPPORTED_CONDITION_TYPES",
    "SUPPORTED_SIGNAL_TYPES",
    "SUPPORTED_ACTION_TYPES",
    "SUPPORTED_SIZING_TYPES",
    "SUPPORTED_UNIVERSE_TYPES",
]
